import Wrapper from '@/components/Wrapper';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'halo.Co',
  description: 'Generated by halo.Co',
  keywords: 'halo, halo.Co, halo.Co',
  robots: 'index, follow',
  icons: {
    icon: '/favicon.ico',
  },
  /* openGraph: {
    title: 'halo.Co',
    description: 'Generated by halo.Co',
    url: 'https://halo.Co',
    siteName: 'halo.Co',
    images: [
      { url: '/favicon.ico' },
    ],
  }, */
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
